[tox]
envlist = py312 # → run test using python 3.12 version

[testenv] # → tells what to do in isolated environment
description = Run unit and integration tests
deps =    # → dependencies required by test environment
    pytest
    pytest-cov
    flake8
    mypy
    black

commands =  # → after creating environment run this command
    # stop the build if there are python error or undefined names in the code
    flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

    flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    mypy src    # → run mypy linter on directory
    black --check src    # → run black linter on directory
    
    pytest tests/unit -v    # → run test in tests directory, verbose output
    pytest tests/integration -v

[pytest]     # → it tells pytest that my tests are located in tests directory
testpaths = tests/unit tests/integration